version: '3'

services:
  db:
    image: redis
    restart: always

  nginx:
    image: nginx
    ports:
      - 9999:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./docker/php/
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    command: bash -c "cd /var/www/html && composer install --no-dev && php-fpm"
    environment:
      - "REDIS_HOST=db"
      - "APP_ENV=production"
      - "APP_DEBUG=false"
